version: 2.0
jobs:
  build:
    docker:
      - image: clojure:openjdk-17-lein-buster
        environment:
          - DB_PORT: 5432
          - CLOJARS_ENVIRONMENT: test
      - image: postgres:12.1
        environment:
          - POSTGRES_USER=clojars
          - POSTGRES_PASSWORD=clojars
          - POSTGRES_DB=clojars
      - image: minio/minio:RELEASE.2023-04-20T17-56-55Z
        command: server /data
        environment:
          MINIO_ROOT_USER: fake-access-key
          MINIO_ROOT_PASSWORD: fake-secret-key
    working_directory: ~/clojars
    steps:
      - checkout
      - restore_cache:
          keys:
            - clojars-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: clojars-{{ checksum "project.clj" }}
      - run: lein do run -m user/migrate, test, uberjar
      - run: ./bin/clj-kondo --lint src test
      - store_test_results:
          path: target/test-results
      - run: mv target/uberjar/clojars-web-*-standalone.jar clojars-uberjar.jar
      - store_artifacts:
          path: clojars-uberjar.jar
          destination: uberjar
